services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: engine
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secretpass12345!!
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
