[project]
name = "fun-with-fast-api"
version = "0.1.0"
description = "Having fun with FastAPI."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
]

[tool.ruff]
lint.extend-select = ["ALL"]
lint.ignore = ["D100", "D203", "D213", "D103", "COM812"]