"""Added Number of employees

Revision ID: c86c89ba2468
Revises: cc97fc981f23
Create Date: 2025-08-28 17:15:05.030772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86c89ba2468'
down_revision: Union[str, Sequence[str], None] = 'cc97fc981f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('employee_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'employee_number')
    # ### end Alembic commands ###
